package GUI.MainScreen;

import Controller.BillDetail_controller;
import Model.Bill.Bill;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tuand
 */
public class BilldetailPanel extends javax.swing.JPanel {

    public Bill b;
    BillDetail_controller billDetail_controller;
    MainScreen mainScreen;
    /**
     * Creates new form billdetail
     */
    public BilldetailPanel(java.awt.Dimension size, MainScreen mainscreen, Bill b) {
        // TODO: combobox
        this.b = b;
        this.setPreferredSize(size);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">     
                         
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bill_ScrollPane = new javax.swing.JScrollPane();
        billunit_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        billunit_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        billunit_table.setModel(tablemodel);
        bill_ScrollPane.setViewportView(billunit_table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 641;
        gridBagConstraints.ipady = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 11, 10);
        add(bill_ScrollPane, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT HOÁ ĐƠN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        add(jLabel1, gridBagConstraints);
        billDetail_controller = new BillDetail_controller(this);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane bill_ScrollPane;
    private javax.swing.JTable billunit_table;
    private javax.swing.JLabel jLabel1;
    public javax.swing.table.DefaultTableModel tablemodel = new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null}
        },
        new String [] {
            "Tên hàng hoá", "Đơn giá", "Số  lượng"
        }
    ) {
        /**
         *
         */
        private static final long serialVersionUID = 1L;
        Class[] types = new Class[] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    };
    // End of variables declaration                   
}
