package GUI.MainScreen;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */

/**
 *
 * @author tuand
 */
public class PromotionPanel extends javax.swing.JPanel {

    /**
     * Creates new form posPanel
     */
    public javax.swing.table.DefaultTableModel tableModel;
    MainScreen mainScreen;

    public PromotionPanel(java.awt.Dimension size, MainScreen mainScreen) {
        this.setPreferredSize(size);
        this.mainScreen = mainScreen;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        promotionTable = new javax.swing.JTable();
        promotionLabel = new javax.swing.JLabel();

        setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        setLayout(new java.awt.GridBagLayout());
        tableModel = new javax.swing.table.DefaultTableModel(new Object[][] {},
                new String[] { "Bar code", "Tên sản phẩm", "Giảm giá" }) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;// This causes all cells to be not editable
            }
        };

        promotionTable.setModel(tableModel);

        jScrollPane1.setViewportView(promotionTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 948;
        gridBagConstraints.ipady = 449;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 38, 10);
        add(jScrollPane1, gridBagConstraints);

        promotionLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        promotionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promotionLabel.setText("KHUYẾN MÃI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 693;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        add(promotionLabel, gridBagConstraints);
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel promotionLabel;
    private javax.swing.JTable promotionTable;
    // End of variables declaration
}
